version: "3.5"
services:
  postgres:
    container_name: rsp-postgres-docker-production
    environment:
      POSTGRES_USER: "annop584"
      POSTGRES_PASSWORD: "annop584@ProdServer"
      PGDATA: "/data/postgres"
      TZ: 'Asia/Bangkok'
      PG_SYSTEM_SHARED_BUFFERS: 256MB
      PG_SYSTEM_MAX_CONNECTIONS: 50000
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=50000"]
    stdin_open: true
    tty: true
    volumes:
       - ./rsp_db/postgres:/data/postgres
    ports:
      - '5433:5432'
    restart: always

  api:
    command: npm run production
    container_name: rsp-back-docker-production
  front:
    command: npm run production
    container_name: rsp-front-docker-production




  